# Generated by Django 3.2.9 on 2022-01-11 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_alter_userproject_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
